import { TaxonomyStatus, TopicClusterStatus } from "@prisma/client";
import Link from "next/link";
import { CsrfField } from "@/components/admin/csrf-field";
import { prisma } from "@/lib/db";
import { taxonomyStatusLabels } from "@/lib/taxonomy";
import { deleteTaxonomyAction, saveCategoryAction, saveTopicAction, saveTopicClusterAction } from "./actions";

export const dynamic = "force-dynamic";
const views = ["categories", "topics", "clusters"] as const;

function Input({ name, value, placeholder }: { name: string; value?: string | number | null; placeholder?: string }) {
  return <input className="mt-2 h-11 w-full rounded-md border border-[#cbd5ce] px-3 text-sm" defaultValue={value ?? ""} name={name} placeholder={placeholder}/>;
}

export default async function TaxonomyPage({ searchParams }: { searchParams: Promise<{ edit?: string; error?: string; marketId?: string; q?: string; saved?: string; view?: string }> }) {
  const params = await searchParams;
  const view = views.includes(params.view as typeof views[number]) ? params.view as typeof views[number] : "categories";
  const marketId = params.marketId || undefined;
  const query = params.q?.trim() || undefined;
  const [markets, categories, topics, clusters, content] = await Promise.all([
    prisma.market.findMany({ orderBy: [{ isGlobal: "desc" }, { code: "asc" }] }),
    prisma.category.findMany({ where: { ...(marketId ? { marketId } : {}), ...(query ? { name: { contains: query, mode: "insensitive" as const } } : {}) }, include: { market: true, parent: true, _count: { select: { children: true, contentItems: true, primaryContent: true } } }, orderBy: [{ marketId: "asc" }, { name: "asc" }] }),
    prisma.topic.findMany({ where: { ...(marketId ? { marketId } : {}), ...(query ? { name: { contains: query, mode: "insensitive" as const } } : {}) }, include: { market: true, topicCluster: true, _count: { select: { contentItems: true, primaryContent: true } } }, orderBy: [{ marketId: "asc" }, { name: "asc" }] }),
    prisma.topicCluster.findMany({ where: { ...(marketId ? { marketId } : {}), ...(query ? { name: { contains: query, mode: "insensitive" as const } } : {}) }, include: { market: true, priorityContentItem: true, _count: { select: { topics: true, anchorTexts: true, internalLinkRules: true } } }, orderBy: [{ priority: "asc" }, { name: "asc" }] }),
    prisma.contentItem.findMany({ where: { status: "PUBLISHED", ...(marketId ? { marketId } : {}) }, orderBy: { title: "asc" }, select: { id: true, title: true, marketId: true, primaryTopic: true } }),
  ]);
  const selectedCategory = categories.find(x => x.id === params.edit);
  const selectedTopic = topics.find(x => x.id === params.edit);
  const selectedCluster = clusters.find(x => x.id === params.edit);
  const categoryDepth = (category: typeof categories[number]) => category.parentId ? (categories.find(x => x.id === category.parentId)?.parentId ? 3 : 2) : 1;
  const link = (nextView: string) => `/admin/taxonomy?view=${nextView}${marketId ? `&marketId=${marketId}` : ""}`;

  return <div className="flex flex-col gap-6">
    <section className="border-b border-[#d9ded7] pb-5"><p className="text-sm font-semibold uppercase tracking-[.14em] text-[#0f766e]">Taxonomy Manager</p><h1 className="mt-2 text-3xl font-semibold text-[#111827]">Categories, topics and clusters</h1><p className="mt-3 text-sm text-[#5f6268]">Build navigation categories up to three levels and organize editorial topics for internal linking.</p></section>
    {params.error && <p className="editor-alert error">{params.error}</p>}{params.saved && <p className="editor-alert success">Taxonomy saved.</p>}
    <nav className="flex flex-wrap gap-2">{views.map(item => <Link className={`rounded-md border px-4 py-2 text-sm font-semibold ${view === item ? "border-[#123c3a] bg-[#123c3a] text-white" : "border-[#cbd5ce] bg-white text-[#123c3a]"}`} href={link(item)} key={item}>{item === "categories" ? "Categories" : item === "topics" ? "Topics" : "Topic clusters"}</Link>)}</nav>
    <form className="grid gap-3 rounded-lg border border-[#d9ded7] bg-white p-4 sm:grid-cols-[1fr_220px_auto]"><input type="hidden" name="view" value={view}/><input className="rounded-md border border-[#cbd5ce] px-3 py-2 text-sm" defaultValue={query} name="q" placeholder="Search by name"/><select className="rounded-md border border-[#cbd5ce] px-3 py-2 text-sm" defaultValue={marketId} name="marketId"><option value="">All markets</option>{markets.map(m => <option value={m.id} key={m.id}>{m.code} — {m.name}</option>)}</select><button className="button button-outline">Filter</button></form>

    {view === "categories" && <><TaxonomyForm title={selectedCategory ? "Edit category" : "New category"} action={saveCategoryAction} cancel={Boolean(selectedCategory)}><input type="hidden" name="id" value={selectedCategory?.id ?? ""}/><label>Name<Input name="name" value={selectedCategory?.name}/></label><label>Slug<Input name="slug" value={selectedCategory?.slug} placeholder="Generated from name"/></label><label>Market<select name="marketId" defaultValue={selectedCategory?.marketId ?? marketId} required>{markets.map(m => <option value={m.id} key={m.id}>{m.code} — {m.name}</option>)}</select></label><label>Parent<select name="parentId" defaultValue={selectedCategory?.parentId ?? ""}><option value="">Root — level 1</option>{categories.filter(c => c.id !== selectedCategory?.id && categoryDepth(c) < 3).map(c => <option value={c.id} key={c.id}>{"— ".repeat(categoryDepth(c) - 1)}{c.name} (level {categoryDepth(c)})</option>)}</select></label><StatusSelect value={selectedCategory?.status}/><label>Description<Input name="description" value={selectedCategory?.description}/></label></TaxonomyForm><SimpleTable headers={["Category","Market","Parent","Level","Status","Usage","Action"]}>{categories.map(c => <tr key={c.id}><Cell><Link className="font-semibold text-[#123c3a] hover:underline" href={`${link("categories")}&edit=${c.id}`}>{"— ".repeat(categoryDepth(c) - 1)}{c.name}</Link><small>{c.slug}</small></Cell><Cell>{c.market.code}</Cell><Cell>{c.parent?.name ?? "Root"}</Cell><Cell>{categoryDepth(c)} / 3</Cell><Cell>{taxonomyStatusLabels[c.status]}</Cell><Cell>{c._count.contentItems + c._count.primaryContent} articles · {c._count.children} children</Cell><Cell><DeleteButton id={c.id} kind="category" disabled={c._count.contentItems + c._count.primaryContent + c._count.children > 0}/></Cell></tr>)}</SimpleTable></>}

    {view === "topics" && <><TaxonomyForm title={selectedTopic ? "Edit topic" : "New topic"} action={saveTopicAction} cancel={Boolean(selectedTopic)}><input type="hidden" name="id" value={selectedTopic?.id ?? ""}/><label>Name<Input name="name" value={selectedTopic?.name}/></label><label>Slug<Input name="slug" value={selectedTopic?.slug}/></label><label>Market<select name="marketId" defaultValue={selectedTopic?.marketId ?? marketId} required>{markets.map(m => <option value={m.id} key={m.id}>{m.code} — {m.name}</option>)}</select></label><label>Cluster<select name="topicClusterId" defaultValue={selectedTopic?.topicClusterId ?? ""}><option value="">No cluster</option>{clusters.map(c => <option value={c.id} key={c.id}>{c.market.code} — {c.name}</option>)}</select></label><StatusSelect value={selectedTopic?.status}/><label>Description<Input name="description" value={selectedTopic?.description}/></label></TaxonomyForm><SimpleTable headers={["Topic","Market","Cluster","Status","Usage","Action"]}>{topics.map(t => <tr key={t.id}><Cell><Link className="font-semibold text-[#123c3a] hover:underline" href={`${link("topics")}&edit=${t.id}`}>{t.name}</Link><small>{t.slug}</small></Cell><Cell>{t.market.code}</Cell><Cell>{t.topicCluster?.name ?? "—"}</Cell><Cell>{taxonomyStatusLabels[t.status]}</Cell><Cell>{t._count.contentItems + t._count.primaryContent}</Cell><Cell><DeleteButton id={t.id} kind="topic" disabled={t._count.contentItems + t._count.primaryContent > 0}/></Cell></tr>)}</SimpleTable></>}

    {view === "clusters" && <><TaxonomyForm title={selectedCluster ? "Edit topic cluster" : "New topic cluster"} action={saveTopicClusterAction} cancel={Boolean(selectedCluster)}><input type="hidden" name="id" value={selectedCluster?.id ?? ""}/><label>Name<Input name="name" value={selectedCluster?.name}/></label><label>Slug<Input name="slug" value={selectedCluster?.slug}/></label><label>Market<select name="marketId" defaultValue={selectedCluster?.marketId ?? marketId} required>{markets.map(m => <option value={m.id} key={m.id}>{m.code} — {m.name}</option>)}</select></label><label>Status<select name="status" defaultValue={selectedCluster?.status ?? TopicClusterStatus.ACTIVE}>{Object.values(TopicClusterStatus).map(s => <option key={s}>{s}</option>)}</select></label><label>Priority<Input name="priority" value={selectedCluster?.priority ?? 100}/></label><label>Priority content<select name="priorityContentItemId" defaultValue={selectedCluster?.priorityContentItemId ?? ""}><option value="">None</option>{content.filter(c => !selectedCluster || c.marketId === selectedCluster.marketId).map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="md:col-span-2">Description<Input name="description" value={selectedCluster?.description}/></label></TaxonomyForm><SimpleTable headers={["Cluster","Market / language","Status","Topics","Links","Priority page","Action"]}>{clusters.map(c => <tr key={c.id}><Cell><Link className="font-semibold text-[#123c3a] hover:underline" href={`${link("clusters")}&edit=${c.id}`}>{c.name}</Link><small>{c.slug}</small></Cell><Cell>{c.market.code} / {c.languageCode}</Cell><Cell>{c.status}</Cell><Cell>{c._count.topics}</Cell><Cell>{c._count.anchorTexts + c._count.internalLinkRules}</Cell><Cell>{c.priorityContentItem?.title ?? "—"}</Cell><Cell><DeleteButton id={c.id} kind="cluster" disabled={c._count.topics + c._count.anchorTexts + c._count.internalLinkRules > 0}/></Cell></tr>)}</SimpleTable></>}
  </div>;
}

function TaxonomyForm({ title, action, cancel, children }: { title: string; action: (data: FormData) => void | Promise<void>; cancel: boolean; children: React.ReactNode }) { return <form action={action} className="rounded-lg border border-[#d9ded7] bg-white p-5"><CsrfField/><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2>{cancel && <Link className="text-sm text-[#0f766e]" href="/admin/taxonomy">Cancel edit</Link>}</div><div className="mt-4 grid gap-4 text-sm font-semibold md:grid-cols-3 [&_select]:mt-2 [&_select]:h-11 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-[#cbd5ce] [&_select]:bg-white [&_select]:px-3">{children}</div><button className="button mt-5" type="submit">Save</button></form>; }
function StatusSelect({ value }: { value?: TaxonomyStatus }) { return <label>Status<select name="status" defaultValue={value ?? TaxonomyStatus.ACTIVE}>{Object.values(TaxonomyStatus).map(s => <option key={s} value={s}>{taxonomyStatusLabels[s]}</option>)}</select></label>; }
function Cell({ children }: { children: React.ReactNode }) { return <td className="px-4 py-4 text-sm text-[#374151]">{children}</td>; }
function SimpleTable({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <section className="overflow-hidden rounded-lg border border-[#d9ded7] bg-white"><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="border-b bg-[#fbfcfb] text-xs uppercase text-[#5f6268]"><tr>{headers.map(h => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-[#eef1ed]">{children}</tbody></table></div></section>; }
function DeleteButton({ id, kind, disabled }: { id: string; kind: string; disabled: boolean }) { return <form action={deleteTaxonomyAction}><CsrfField/><input type="hidden" name="id" value={id}/><input type="hidden" name="kind" value={kind}/><button className="text-xs font-semibold text-[#9a3412] disabled:text-[#9ca3af]" disabled={disabled} type="submit">{disabled ? "In use" : "Delete"}</button></form>; }
